/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DevMetaRouteImport } from './routes/dev.meta'
import { Route as DashboardWritingRouteImport } from './routes/dashboard.writing'
import { Route as DashboardVocabularyRouteImport } from './routes/dashboard.vocabulary'
import { Route as DashboardVideosRouteImport } from './routes/dashboard.videos'
import { Route as DashboardSpeakingRouteImport } from './routes/dashboard.speaking'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReadingRouteImport } from './routes/dashboard.reading'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardPlanRouteImport } from './routes/dashboard.plan'
import { Route as DashboardMockTestsRouteImport } from './routes/dashboard.mock-tests'
import { Route as DashboardLiveRouteImport } from './routes/dashboard.live'
import { Route as DashboardListeningRouteImport } from './routes/dashboard.listening'
import { Route as DashboardIntelligenceRouteImport } from './routes/dashboard.intelligence'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as ChannelIdRouteImport } from './routes/channel.$id'
import { Route as ApiSocialPreviewRouteImport } from './routes/api/social-preview'
import { Route as AdminYoutubeRouteImport } from './routes/admin.youtube'
import { Route as AdminVocabularyRouteImport } from './routes/admin.vocabulary'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminSpeakingAiRouteImport } from './routes/admin.speaking-ai'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminPredictionsRouteImport } from './routes/admin.predictions'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminMockTestsRouteImport } from './routes/admin.mock-tests'
import { Route as AdminMailRouteImport } from './routes/admin.mail'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as ApiPublicYtDiscoverCronRouteImport } from './routes/api/public/yt-discover-cron'
import { Route as ApiPublicYoutubeSyncCronRouteImport } from './routes/api/public/youtube-sync-cron'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DevMetaRoute = DevMetaRouteImport.update({
  id: '/dev/meta',
  path: '/dev/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWritingRoute = DashboardWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVocabularyRoute = DashboardVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVideosRoute = DashboardVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpeakingRoute = DashboardSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReadingRoute = DashboardReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanRoute = DashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMockTestsRoute = DashboardMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListeningRoute = DashboardListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntelligenceRoute = DashboardIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ChannelIdRoute = ChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialPreviewRoute = ApiSocialPreviewRouteImport.update({
  id: '/api/social-preview',
  path: '/api/social-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVocabularyRoute = AdminVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakingAiRoute = AdminSpeakingAiRouteImport.update({
  id: '/speaking-ai',
  path: '/speaking-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMockTestsRoute = AdminMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicYtDiscoverCronRoute = ApiPublicYtDiscoverCronRouteImport.update({
  id: '/api/public/yt-discover-cron',
  path: '/api/public/yt-discover-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeSyncCronRoute =
  ApiPublicYoutubeSyncCronRouteImport.update({
    id: '/api/public/youtube-sync-cron',
    path: '/api/public/youtube-sync-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/videos': typeof VideosRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speaking-ai': typeof AdminSpeakingAiRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/api/social-preview': typeof ApiSocialPreviewRoute
  '/channel/$id': typeof ChannelIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/listening': typeof DashboardListeningRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/mock-tests': typeof DashboardMockTestsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard/vocabulary': typeof DashboardVocabularyRoute
  '/dashboard/writing': typeof DashboardWritingRoute
  '/dev/meta': typeof DevMetaRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/youtube-sync-cron': typeof ApiPublicYoutubeSyncCronRoute
  '/api/public/yt-discover-cron': typeof ApiPublicYtDiscoverCronRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/videos': typeof VideosRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speaking-ai': typeof AdminSpeakingAiRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/api/social-preview': typeof ApiSocialPreviewRoute
  '/channel/$id': typeof ChannelIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/listening': typeof DashboardListeningRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/mock-tests': typeof DashboardMockTestsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard/vocabulary': typeof DashboardVocabularyRoute
  '/dashboard/writing': typeof DashboardWritingRoute
  '/dev/meta': typeof DevMetaRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/youtube-sync-cron': typeof ApiPublicYoutubeSyncCronRoute
  '/api/public/yt-discover-cron': typeof ApiPublicYtDiscoverCronRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/videos': typeof VideosRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/mock-tests': typeof AdminMockTestsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speaking-ai': typeof AdminSpeakingAiRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/api/social-preview': typeof ApiSocialPreviewRoute
  '/channel/$id': typeof ChannelIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/listening': typeof DashboardListeningRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/mock-tests': typeof DashboardMockTestsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard/vocabulary': typeof DashboardVocabularyRoute
  '/dashboard/writing': typeof DashboardWritingRoute
  '/dev/meta': typeof DevMetaRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/youtube-sync-cron': typeof ApiPublicYoutubeSyncCronRoute
  '/api/public/yt-discover-cron': typeof ApiPublicYtDiscoverCronRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsors'
    | '/videos'
    | '/admin/admins'
    | '/admin/api'
    | '/admin/content'
    | '/admin/live'
    | '/admin/mail'
    | '/admin/mock-tests'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/predictions'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/speaking-ai'
    | '/admin/sponsors'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin/youtube'
    | '/api/social-preview'
    | '/channel/$id'
    | '/dashboard/billing'
    | '/dashboard/intelligence'
    | '/dashboard/listening'
    | '/dashboard/live'
    | '/dashboard/mock-tests'
    | '/dashboard/plan'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/videos'
    | '/dashboard/vocabulary'
    | '/dashboard/writing'
    | '/dev/meta'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/youtube-sync-cron'
    | '/api/public/yt-discover-cron'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsors'
    | '/videos'
    | '/admin/admins'
    | '/admin/api'
    | '/admin/content'
    | '/admin/live'
    | '/admin/mail'
    | '/admin/mock-tests'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/predictions'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/speaking-ai'
    | '/admin/sponsors'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin/youtube'
    | '/api/social-preview'
    | '/channel/$id'
    | '/dashboard/billing'
    | '/dashboard/intelligence'
    | '/dashboard/listening'
    | '/dashboard/live'
    | '/dashboard/mock-tests'
    | '/dashboard/plan'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/videos'
    | '/dashboard/vocabulary'
    | '/dashboard/writing'
    | '/dev/meta'
    | '/admin'
    | '/dashboard'
    | '/api/public/youtube-sync-cron'
    | '/api/public/yt-discover-cron'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsors'
    | '/videos'
    | '/admin/admins'
    | '/admin/api'
    | '/admin/content'
    | '/admin/live'
    | '/admin/mail'
    | '/admin/mock-tests'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/predictions'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/speaking-ai'
    | '/admin/sponsors'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin/youtube'
    | '/api/social-preview'
    | '/channel/$id'
    | '/dashboard/billing'
    | '/dashboard/intelligence'
    | '/dashboard/listening'
    | '/dashboard/live'
    | '/dashboard/mock-tests'
    | '/dashboard/plan'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/videos'
    | '/dashboard/vocabulary'
    | '/dashboard/writing'
    | '/dev/meta'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/youtube-sync-cron'
    | '/api/public/yt-discover-cron'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  VideosRoute: typeof VideosRoute
  ApiSocialPreviewRoute: typeof ApiSocialPreviewRoute
  ChannelIdRoute: typeof ChannelIdRoute
  DevMetaRoute: typeof DevMetaRoute
  ApiPublicYoutubeSyncCronRoute: typeof ApiPublicYoutubeSyncCronRoute
  ApiPublicYtDiscoverCronRoute: typeof ApiPublicYtDiscoverCronRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dev/meta': {
      id: '/dev/meta'
      path: '/dev/meta'
      fullPath: '/dev/meta'
      preLoaderRoute: typeof DevMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/writing': {
      id: '/dashboard/writing'
      path: '/writing'
      fullPath: '/dashboard/writing'
      preLoaderRoute: typeof DashboardWritingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vocabulary': {
      id: '/dashboard/vocabulary'
      path: '/vocabulary'
      fullPath: '/dashboard/vocabulary'
      preLoaderRoute: typeof DashboardVocabularyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/videos': {
      id: '/dashboard/videos'
      path: '/videos'
      fullPath: '/dashboard/videos'
      preLoaderRoute: typeof DashboardVideosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/speaking': {
      id: '/dashboard/speaking'
      path: '/speaking'
      fullPath: '/dashboard/speaking'
      preLoaderRoute: typeof DashboardSpeakingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reading': {
      id: '/dashboard/reading'
      path: '/reading'
      fullPath: '/dashboard/reading'
      preLoaderRoute: typeof DashboardReadingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan': {
      id: '/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof DashboardPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mock-tests': {
      id: '/dashboard/mock-tests'
      path: '/mock-tests'
      fullPath: '/dashboard/mock-tests'
      preLoaderRoute: typeof DashboardMockTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listening': {
      id: '/dashboard/listening'
      path: '/listening'
      fullPath: '/dashboard/listening'
      preLoaderRoute: typeof DashboardListeningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intelligence': {
      id: '/dashboard/intelligence'
      path: '/intelligence'
      fullPath: '/dashboard/intelligence'
      preLoaderRoute: typeof DashboardIntelligenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/channel/$id': {
      id: '/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof ChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-preview': {
      id: '/api/social-preview'
      path: '/api/social-preview'
      fullPath: '/api/social-preview'
      preLoaderRoute: typeof ApiSocialPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vocabulary': {
      id: '/admin/vocabulary'
      path: '/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AdminVocabularyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speaking-ai': {
      id: '/admin/speaking-ai'
      path: '/speaking-ai'
      fullPath: '/admin/speaking-ai'
      preLoaderRoute: typeof AdminSpeakingAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mock-tests': {
      id: '/admin/mock-tests'
      path: '/mock-tests'
      fullPath: '/admin/mock-tests'
      preLoaderRoute: typeof AdminMockTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail': {
      id: '/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/yt-discover-cron': {
      id: '/api/public/yt-discover-cron'
      path: '/api/public/yt-discover-cron'
      fullPath: '/api/public/yt-discover-cron'
      preLoaderRoute: typeof ApiPublicYtDiscoverCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube-sync-cron': {
      id: '/api/public/youtube-sync-cron'
      path: '/api/public/youtube-sync-cron'
      fullPath: '/api/public/youtube-sync-cron'
      preLoaderRoute: typeof ApiPublicYoutubeSyncCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminMockTestsRoute: typeof AdminMockTestsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpeakingAiRoute: typeof AdminSpeakingAiRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVocabularyRoute: typeof AdminVocabularyRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminContentRoute: AdminContentRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMailRoute: AdminMailRoute,
  AdminMockTestsRoute: AdminMockTestsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpeakingAiRoute: AdminSpeakingAiRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVocabularyRoute: AdminVocabularyRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardIntelligenceRoute: typeof DashboardIntelligenceRoute
  DashboardListeningRoute: typeof DashboardListeningRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMockTestsRoute: typeof DashboardMockTestsRoute
  DashboardPlanRoute: typeof DashboardPlanRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardReadingRoute: typeof DashboardReadingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpeakingRoute: typeof DashboardSpeakingRoute
  DashboardVideosRoute: typeof DashboardVideosRoute
  DashboardVocabularyRoute: typeof DashboardVocabularyRoute
  DashboardWritingRoute: typeof DashboardWritingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardIntelligenceRoute: DashboardIntelligenceRoute,
  DashboardListeningRoute: DashboardListeningRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMockTestsRoute: DashboardMockTestsRoute,
  DashboardPlanRoute: DashboardPlanRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardReadingRoute: DashboardReadingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpeakingRoute: DashboardSpeakingRoute,
  DashboardVideosRoute: DashboardVideosRoute,
  DashboardVocabularyRoute: DashboardVocabularyRoute,
  DashboardWritingRoute: DashboardWritingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  VideosRoute: VideosRoute,
  ApiSocialPreviewRoute: ApiSocialPreviewRoute,
  ChannelIdRoute: ChannelIdRoute,
  DevMetaRoute: DevMetaRoute,
  ApiPublicYoutubeSyncCronRoute: ApiPublicYoutubeSyncCronRoute,
  ApiPublicYtDiscoverCronRoute: ApiPublicYtDiscoverCronRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
